NVIDIA/TensorRT-Incubator

tripy/Dockerfile

`mlir-tensorrt` no longer requires protobuf installation.

Remove protobuf installation

---

tripy/CONTRIBUTING.md
tripy/Dockerfile
tripy/README.md

https://nvidia.github.io/TensorRT-Incubator/packages.html (generated by https://github.com/NVIDIA/TensorRT-Incubator/pull/39)

Use packages.html file for identifying packages required for tripy

---

tripy/tests/backend/test_compiler_api.py
tripy/tripy/common/shape_bounds.py
tripy/tripy/flat_ir/flat_ir.py
tripy/tripy/frontend/trace/trace.py

This PR eases the translation to MLIR program via ensuring static shape arguments are not expressed as dynamic shape args with shape profile of `min==max==opt`.
New function signature after this change:
```py
module @ins_a_b_outs_t8_1 {
func.func @main(%arg0: tensor<?xf32> {tensorrt.shape_profile = #tensorrt.shape_profile<min = [1], opt = [2], max = [5]>}, %arg1: tensor<1xf32>) -> tensor<?xf32> {
}
}
```
Old function signature:
```py
func.func @main(%arg0: tensor<?xf32> {tensorrt.shape_profile = #tensorrt.shape_profile<min = [1], opt = [2], max = [5]>}, %arg1: tensor<?xf32> {tensorrt.shape_profile = #tensorrt.shape_profile<min = [1], opt = [1], max = [1]>}) -> tensor<?xf32> {
```

Ease translation of known static shape args to mlir

---

tripy/tests/helper.py
tripy/tests/tools/test_stablehlo_runner.py
tripy/tripy/backend/mlir/compiler.py
tripy/tripy/backend/mlir/utils.py

Utilize `get_asm(large_elements_limit=32)` for printing mlir textual program.
Thanks @christopherbate for pointing this out.

Remove remove_constants utils

---

tripy/tests/frontend/test_tensor.py
tripy/tripy/frontend/tensor.py

All other types except for float8 and int4 can be converted to a Python list without requiring an explicit cast. Update test to ensure round-tripping a python sequence from Tripy does not change data type except for `float8` where an explicit cast is required.

Only Cast float8 and int4 to float32 when converting to Python list

---

tripy/.pre-commit-config.yaml

We need to list all `repo` under a single `repos` for pre-commit hooks to work. Until now only the last hook i.e. `add-license` was working.

Fix code formatting pre-commit hook

---

mlir-tensorrt/executor/lib/Utils/TensorRTDynamicLoader/TensorRTDynamicLoader.cpp

- Updates MLIR-TRT to include major version when loading TRT. The libraries that ship with the wheels always include the major version and do not provide a `libvninfer.so` symlink.

Updates MLIR-TRT to include major version when loading TRT

---

mlir-tensorrt/.gitignore

For some reason downloaded llvm-project in not getting ignored by .gitignore with `**/llvm-project/**` pattern, add `**/llvm-project/` pattern which works.

Fix llvm-project .gitignore

---

mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/test/python/mlir_tensorrt_runtime/test_create_memref.py

- Enable read-only access to the underlying pointer of MemRefValue in Python bindings
- Throw an exception when creating a device view over a host pointer or vice versa.
- Extend memref tests to verify against implicit memory copies and incorrect usage.
This is a pre-requisite to https://github.com/NVIDIA/TensorRT-Incubator/pull/74/.
Signed-off-by: Jhalak Patel <jhalakp@nvidia.com>

Add read-only access to MemRefValue underlying pointer in Python bindings

---

mlir-tensorrt/compiler/lib/Conversion/StablehloToTensorRT/CMakeLists.txt
mlir-tensorrt/tools/MlirTensorRtOpt.cpp

[mlir-tensorrt] fix failure due to double registration and missing link deps
This change fixes a test failure that arises only when assertions are on:
the registration for one of the passes/pipelines was being called twice.
This also fixes a sporadic build failure to to missing dependencies listed
in the StableHLOToTensorRT conversion library declaration.
Signed-off-by: Christopher Bate <cbate@nvidia.com>

[mlir-tensorrt] fix failure due to double registration

---

tripy/tests/backend/test_compiler_api.py
tripy/tripy/backend/compiler_api.py

Catch (and replace with more informative) the error thrown by backend when input shapes don't match expected bounds

Report informative error when input shapes are out of bounds.

---

tripy/CHANGELOG.md
tripy/Dockerfile
tripy/pyproject.toml
tripy/tests/common/test_array.py
tripy/tests/common/test_utils.py
tripy/tests/frontend/test_tensor.py
tripy/tests/integration/test_dequantize.py
tripy/tests/integration/test_functional.py
tripy/tests/integration/test_quantize.py
tripy/tripy/__init__.py
tripy/tripy/flat_ir/ops/plugin.py

- Greatly reduces the size of the development container by using a smaller base image and cutting out many unnecessary packages.
- Adds TRT as a direct dependency of Tripy since in `plugin.py`, we need to load it to determine the major version of `libnvinfer_plugin`.
- Removes CHANGELOG as we can automatically generate release notes via GitHub releases.
- Removes JAX as a test dependency and the tests that use it. We were previously using it to test interoperability using DLPack, but we already test that  with torch/cupy/numpy. Adding JAX provides no additional coverage and unnecessarily bloats the container.
- Bumps version to 0.0.2

Reduces container size, fixes Tripy dependencies, bumps version

---

tripy/tests/frontend/module/conftest.py
tripy/tests/frontend/module/test_module.py
tripy/tripy/frontend/module/module.py

Updates homogenous container check to allow subclasses that all derive from the same superclass to be "mixed" in the same container. This effectively allows lists/dicts of modules or params to be registered in the state dict. 
L0 test: 1959 passed, 47 skipped, 1 deselected, 1 warning

Allow containers of homogenous superclass in state dict

---

mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h
mlir-tensorrt/executor/include/mlir-executor/Runtime/API/API.h
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/executor/lib/Runtime/API/API.cpp
mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/test/python/mlir_tensorrt_runtime/test_create_memref.py

RuntimeClient uses the AllocTracker class to manage the lifetime of pointers.
A pointer could be owned internally or externally and referenced internally or externally. The current implementation only accounts for infernal references. This PR extends AllocTracker to account for external reference and fixes a bug where we would deallocate a memref even if it is being referenced externally (eg. by a DL managed tensor owned by numpy/cupy etc.)
Before this change:
```
Test internally owned Array -> client.host_memref -> externally referenced numpy.from_dlpack
Numpy Array:  [5.4155870e-39 3.2533946e-41 2.1489487e-11]
```
After this change:
```
Test internally owned Array -> client.host_memref -> externally referenced numpy.from_dlpack
Numpy Array:  [5. 4. 2.]
```
Signed-off-by: Jhalak Patel …

Add external reference counting to AllocTracker

---

mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/test/python/mlir_tensorrt_runtime/test_create_memref.py

This function greatly simplifies Tripy's Array implementation. We want to be able to handle memref creation from all types that implement the `__dlpack__()` interface rather than the limited set we currently support. This function should allow us to achieve this. The corresponding Tripy changes are #72.

Added function `create_memref_view_from_dlpack`

---

mlir-tensorrt/test/python/mlir_tensorrt_runtime/test_create_memref.py

This PR formats `test_create_memref.py` using black formatter.

[NFC] Fix `test_create_memref.py` formatting.

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py
tripy/tripy/frontend/trace/ops/base.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/cast.py
tripy/tripy/frontend/trace/ops/concatenate.py
tripy/tripy/frontend/trace/ops/copy.py
tripy/tripy/frontend/trace/ops/expand.py
tripy/tripy/frontend/trace/ops/fill.py
tripy/tripy/frontend/trace/ops/flip.py
tripy/tripy/frontend/trace/ops/gather.py
tripy/tripy/frontend/trace/ops/permute.py
tripy/tripy/frontend/trace/ops/reshape.py
tripy/tripy/frontend/trace/ops/shape.py
tripy/tripy/frontend/trace/ops/slice.py
tripy/tripy/frontend/trace/ops/split.py
tripy/tripy/frontend/trace/ops/utils.py
tripy/tripy/frontend/trace/ops/where.py

For some cases, it is useful to know the length of a `tp.Shape` without executing the model. This PR adds a method `infer_len` that allows operators to specify how to statically infer the length of `Shape` outputs when possible (it is always optional). Test cases are added.

[Tripy] Add `__len__` for `tp.Shape` and infer length statically when possible

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py

- Adds `Shape.__ne__()` method so that shapes can be conveniently checked for inequality.
- Fixes logic error where `Shape.__eq__()` would ignore checking rank. This would lead to an error when comparing shape's with different ranks.
- Adds shape inequality test cases for shapes with different and same ranks.

Add `Shape.__ne__()`

---

.github/CODEOWNERS
.github/workflows/post-merge-container-update-mlir-tensorrt.yml

This PR adds a GitHub workflow to create new docker image if changes are made in `build_tools/docker/Dockerfile`, `python/requirements-dev.txt` or `python/requirements.txt`.

Add GitHub workflow to create docker image for `mlir-tensorrt` project

---

tripy/tests/integration/test_reduce.py
tripy/tripy/frontend/trace/ops/reduce.py

- Adds test cases for multiple negative reduce dims, e.g.
```python
a = tp.ones((5,5,5))
tp.sum(a, dim=[-2,-1]
```
- Fixes the `_reduce_impl` to ensure negatives are sorted in decreasing order when performing `unsqueeze`

Fix reduce dims to work with multiple negative dims

---

tripy/tests/integration/test_groupnorm.py
tripy/tests/integration/test_layernorm.py
tripy/tripy/frontend/module/groupnorm.py
tripy/tripy/frontend/module/layernorm.py

- Make  the `normalized_shape` argument 1:1 with Torch. Previously, our API only supported taking a single integer for the normalization dimension. Now, a list of integers can be provided.
- Add integration tests for `tp.LayerNorm` and `tp.GroupNorm`

Make `tp.Layernorm` 1:1 with torch

---

.github/workflows/tripy-l1.yml

Not successful figuring out how to commit to `gh-pages` branch, the contents are very different. Disabling the doc deployment job for now.

Disable doc deployment in L1

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py

Since we are treating `tp.Shape` as a collection, it may also make sense to iterate over them. This PR adds a very simple iterator implementation to `tp.Shape`. Another way we could implement it would be to override `__getitem__` to throw an exception if it gives an out-of-bounds access and then use the default iterator, but this is likely simpler.

[Tripy] Add iterator implementation for `tp.Shape`

---

tripy/CONTRIBUTING.md

`docker run` by default will only pull an image if it is entirely missing, so the command given in `CONTRIBUTING.md` will not update the image if it had been pulled before. This change adds the `--pull always` setting in the example command so that it would check for an update before running.

[Tripy][Docs] Recommend the use of `--pull always` to update the image in the contributing doc

---

tripy/.gitignore
tripy/CONTRIBUTING.md
tripy/docs/post0_developer_guides/debugging.md
tripy/pyproject.toml
tripy/tests/README.md
tripy/tests/frontend/test_tensor.py
tripy/tests/utils/test_stack_info.py
tripy/tripy/common/exception.py
tripy/tripy/frontend/utils.py
tripy/tripy/utils/stack_info.py

Enables pytest profiling
- Updates container to include tooling to enable profiling our test suite.
- Updates README with instructions on how to use profiling tooling.
Greatly speeds up `get_stack_info()`
- Updates `get_stack_info()` to no longer use `inspect` APIs, which are extremely
slow, but instead work with the frames directly.
- Updates `StackInfo` with a `fetch_source_code()` method which allows us to defer
the fetching of source code (extremely slow due to file I/O) until the point
where we actually require it, which is typically when we throw an exception.
This greatly speeds up Tripy execution in general, including our tests:
Before:
```
=================== 1691 passed, 54 skipped, 2549 deselected in 311.22s (0:05:11) ==================
=
```
After:
```
===================== …
```

Adds test profiling, speeds up tests

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py

This PR corrects a small bug with the `__eq__` implementation for `tp.Shape`: The comparison was checking the `len` of the `shape` field of the shape, but it should actually be checking the length of the `tp.Shape` itself. 
Note: The test case that was included in the unit tests worked "by accident" because the shape in it was length 1, which is broadcasted up to other shapes' lengths. Without this change, the test would fail if comparing two shapes of different lengths where neither is length 1.

[Tripy][Bugfix] Ensure shape `__eq__` works with different lengths

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py

Since we are treating `tp.Shape` more like a `Sequence` than a `Tensor`, we can treat `*` similarly to `+` and have a separate `multiply` to do elementwise multiplication while treating `*` as tiling.
This PR also improves the doc comment for `Shape`, so that the generated doc page clearly explains how `+` and `*` work differently compared to `Tensor`.

[Tripy] Override `__mul__` for `tp.Shape`s to work like `__mul__` for Python lists

---

tripy/tests/backend/test_stream.py
tripy/tripy/backend/compiler_api.py
tripy/tripy/backend/mlir/executor.py
tripy/tripy/backend/mlir/memref.py
tripy/tripy/frontend/tensor.py

Changes in this MR:
1. Adds `tp.Stream` interface. (supports streams with priority 0 as of now). Allows getting default stream.
2. Tripy execution will be async by default and user is expected to call `stream.synchronize()`.
3. In case the user does not set stream for execution, Tripy will use default stream. The user is still expected to call synchronize and can call synchronize on the class which invokes sync on default stream. (ie. `tp.synchronize()`.

Re-introduce tp.Stream

---

tripy/docs/conf.py
tripy/tests/frontend/ops/test_repeat.py
tripy/tests/frontend/test_shape.py
tripy/tests/integration/test_reduce.py
tripy/tests/integration/test_repeat.py
tripy/tests/integration/test_unsqueeze.py
tripy/tests/spec_verification/object_builders.py
tripy/tests/spec_verification/test_dtype_constraints.py
tripy/tripy/common/datatype.py
tripy/tripy/constraints.py
tripy/tripy/flat_ir/ops/add.py
tripy/tripy/flat_ir/ops/reshape.py
tripy/tripy/frontend/module/layernorm.py
tripy/tripy/frontend/ops/allclose.py
tripy/tripy/frontend/ops/relu.py
tripy/tripy/frontend/ops/repeat.py
tripy/tripy/frontend/ops/tensor_initializers.py
tripy/tripy/frontend/trace/ops/reduce.py
tripy/tripy/frontend/trace/ops/unsqueeze.py
tripy/tripy/frontend/utils.py
tripy/tripy/function_registry.py
tripy/tripy/utils/utils.py

- Updates unsqueeze test to check that shape is correct
- Updates docstrings in some functions to print outputs, disables `bool` in allclose
- Miscellaneous bug fixes in various operations
- Adds a `tp.repeat` API. The API is currently constrained to accepting only a single integer value for
`repeats` since this greatly simplifies the implementation.
- Introduces a `process_dim` decorator which handles negative dimensions in API functions.
- Various minor fixes to dtype constraint checking. Also merges the positive/negative
dtype constraints test into one so it's easier to run all the tests for a given op.

Adds `repeat` API, various other fixes

---

tripy/.pre-commit-config.yaml
tripy/Dockerfile
tripy/docs/pre0_user_guides/01-quantization.md
tripy/pyproject.toml
tripy/tests/frontend/ops/test_repeat.py
tripy/tests/integration/test_repeat.py
tripy/tests/spec_verification/test_dtype_constraints.py
tripy/tools/add_copyright.py
tripy/tripy/frontend/ops/repeat.py

- Updates copyright hook to update existing files    
- Updates the copyright hook to accept file arguments directly from `pre-commit`.  
- Updates copyright hook to also update existing files when required.
- Fixes an error in negative dtype constraint tests where output types were not checked
- Adds license to repeat files

Fix dtype constraints and copyright hook

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py
tripy/tripy/frontend/trace/ops/base.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/cast.py
tripy/tripy/frontend/trace/ops/expand.py
tripy/tripy/frontend/trace/ops/matmul.py
tripy/tripy/frontend/trace/ops/reshape.py
tripy/tripy/frontend/trace/ops/shape.py
tripy/tripy/frontend/trace/ops/slice.py
tripy/tripy/frontend/trace/ops/utils.py
tripy/tripy/frontend/trace/ops/where.py

This PR adds `ScalarShape` to Tripy which is encodes a value that is sliced out of a `Shape` tensor.

Add scalar shape class to Tripy

---

tripy/tests/integration/test_arange.py
tripy/tests/integration/test_full.py
tripy/tests/integration/test_stack.py
tripy/tripy/frontend/ops/stack.py
tripy/tripy/frontend/ops/tensor_initializers.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/concatenate.py
tripy/tripy/frontend/trace/ops/fill.py
tripy/tripy/frontend/utils.py
tripy/tripy/function_registry.py

This PR adds the following:
1. `arange`: allows start, stop or size  (or all) to be tensors.
2. Adds `floordiv` operation.
3. Allows fill operation to accept value as input.

Fix arange, add floordiv, fix Fill op

---

tripy/tests/integration/test_arange.py
tripy/tripy/frontend/ops/tensor_initializers.py
tripy/tripy/frontend/shape.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/expand.py
tripy/tripy/frontend/trace/ops/fill.py
tripy/tripy/frontend/trace/ops/iota.py
tripy/tripy/frontend/trace/ops/reshape.py
tripy/tripy/frontend/trace/ops/slice.py

Fixes below bug: 
```
--> /tripy/examples/nanogpt/model.py:92 in <lambda>()
|
92 |         multi_heads = lambda x: tp.transpose(tp.reshape(x, multi_head_output_shape), 1, 2)
| 
Could not find an implementation for function: 'reshape'.
Candidate overloads were:
--> /tripy/tripy/constraints.py:75 in reshape()
|
75 | def reshape(input: "tripy.Tensor", shape: Union["tripy.Shape", Sequence[Union[int, "tripy.Tensor"]]]) -> "tripy.Tensor":
76 |     ...
| 
Not a valid overload because: For parameter: 'shape', expected an instance of type: 'typing.Union[ForwardRef('tripy.Shape'), typing.Sequence[typing.Union[int, ForwardRef('tripy.Tensor')]]]' but got argument of type: 'Tensor'.
```

Fix reshape annotation to allow tensor input

---

tripy/tests/frontend/test_shape.py
tripy/tripy/frontend/shape.py

Noticed a small error: The `__str__` method for `ShapeScalar` assumed that evaluating the scalar would give a list output, resulting in a type error, since the actual result is a scalar. This PR fixes that and adds a check to the unit tests.

[Tripy][Bugfix] Use correct types in `__str__` method for `ShapeScalar`

---

tripy/docs/post0_developer_guides/how-to-add-new-ops.md
tripy/tests/frontend/test_utils.py
tripy/tests/frontend/trace/ops/test_binary_elementwise.py
tripy/tripy/common/exception.py
tripy/tripy/frontend/ops/tensor_initializers.py
tripy/tripy/frontend/shape.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/dequantize.py
tripy/tripy/frontend/trace/ops/expand.py
tripy/tripy/frontend/trace/ops/fill.py
tripy/tripy/frontend/trace/ops/iota.py
tripy/tripy/frontend/trace/ops/quantize.py
tripy/tripy/frontend/trace/ops/reduce.py
tripy/tripy/frontend/trace/ops/reshape.py
tripy/tripy/frontend/utils.py

Addresses issue #214 and separates shape argument conversion from the `convert_inputs_to_tensors` decorator. Since most uses of the shape argument conversion would only convert one argument (usually named shape), this decorator takes a list of arguments to convert rather than converting all arguments by default. It also does not accept arguments that aren't sequences of Python numbers or Tripy Tensors, since it would make less sense to allow external data formats to silently pass through in cases that aren't operator overloads.

[Tripy] Separate converting shape args from converting tensor args

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/Verification.cpp
mlir-tensorrt/tensorrt/test/TensorRT/invalid.mlir
mlir-tensorrt/tensorrt/test/TensorRT/roundtrip.mlir
mlir-tensorrt/test/Target/TensorRT/resize.mlir

Add `output_shape` argument to all resize ops in TRT dialect.

Add output_shape argument to resize ops

---

tripy/docs/post0_developer_guides/design-decisions.md
tripy/docs/pre0_user_guides/02-compiler.md
tripy/tests/flat_ir/ops/test_gather.py
tripy/tests/helper.py
tripy/tests/spec_verification/object_builders.py
tripy/tests/spec_verification/test_dtype_constraints.py
tripy/tests/test_files.py
tripy/tripy/common/exception.py
tripy/tripy/export.py
tripy/tripy/frontend/module/parameter.py
tripy/tripy/frontend/ops/allclose.py
tripy/tripy/frontend/ops/cumsum.py
tripy/tripy/frontend/ops/outer.py
tripy/tripy/frontend/ops/tensor_initializers.py
tripy/tripy/frontend/shape.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/cast.py
tripy/tripy/frontend/trace/ops/convolution.py
tripy/tripy/frontend/trace/ops/expand.py
tripy/tripy/frontend/trace/ops/fill.py
tripy/tripy/frontend/trace/ops/iota.py
tripy/tripy/frontend/trace/ops/pooling.py
tripy/tripy/frontend/trace/ops/reduce.py
tripy/tripy/frontend/trace/ops/reshape.py
tripy/tripy/frontend/trace/ops/slice.py
tripy/tripy/frontend/utils.py
tripy/tripy/function_registry.py
tripy/tripy/types.py

- Adds tests to ensure we only use ASCII characters in our code and markdown files. Some non-ASCII characters that look like ASCII characters were breaking tests that make assumptions about the encoding.
- Updates dtype constraint tests to properly construct inputs for various APIs.
- Moves dtype constraint tests to L0 since they only add about 20 seconds and were breaking very often otherwise.
- Updates binary elementwise ops to only return `ShapeScalar`s if *all* inputs are also `ShapeScalar`s.
- Corrects dtype constraints for several APIs.
- Simplifies `mean` implementation.
- Corrects type annotations for some APIs and introduces a `ShapeLike` type.
- Adds support for `Optional` during type checking.
- Updates `convert_inputs_to_tensors` to now potentially convert tensors to `Tensor` …

Various bug fixes to fix L1 tests

---

mlir-tensorrt/tensorrt/CMakeLists.txt
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TypeInferenceInterfaceImpls.cpp
mlir-tensorrt/tensorrt/tensorrt-opt/CMakeLists.txt
mlir-tensorrt/tensorrt/tensorrt-opt/tensorrt-opt.cpp
mlir-tensorrt/tensorrt/test/TensorRT/dynamic-shape-inference.mlir
mlir-tensorrt/tensorrt/test/lib/CMakeLists.txt
mlir-tensorrt/tensorrt/test/lib/TensorRT/CMakeLists.txt
mlir-tensorrt/tensorrt/test/lib/TensorRT/TestTypeInferencePass.cpp

This MR needs https://github.com/NVIDIA/TensorRT-Incubator/pull/231.

Add shape inference for resize ops in TRT dialect

---

tripy/tripy/backend/mlir/memref.py

Several tests creating memref for host data with stream are failing https://github.com/NVIDIA/TensorRT-Incubator/commit/54f98196d4f72f02f4dc97afa24963e8ee608d6d#diff-d10f6cc35783e94f23c4ff7a348efac1ede25554509e0631d82ba6701f838455R71.
It looks like MLIR-TRT is now propagating the stream correctly. Failure is observed in following check:
```
if (type == PointerType::host) {
assert(alignment && !stream &&
"expected alignment, no stream for host allocation");
...
}
```
Tripy side fix is to pass None stream for host memref data.

Create memerf with None stream for host data

---

.github/workflows/mlir-tensorrt-ci.yml

This MR adds commit message check in `mlir-tensorrt` CI. If commit message check fails, it prints out
commit message and canonical format expected.

[mlir-tensorrt] Add commit message check to CI

---

mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h
mlir-tensorrt/executor/include/mlir-executor/Runtime/API/API.h
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/executor/lib/Runtime/API/API.cpp
mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/test/python/mlir_tensorrt_runtime/test_create_memref.py

Add optional stride validation in `MemRefValue::create` to compute canonical stride and compare against given strides while creaing a memref view from DLPack tensors. We need to handle special cases for zero-sized and unit-sized dimensions since frameworks deal with them arbitrarily while converting to the corresponding DLPack tensor. Add Python tests to verify both canonical and non-canonical stride validation.

[API/MemRef] Implement canonical stride validation for MemRefValue creation

---

tripy/tests/backend/mlir/test_utils.py
tripy/tests/frontend/test_stride.py
tripy/tests/integration/test_allclose.py
tripy/tests/integration/test_quantize.py
tripy/tripy/backend/api/executable.py
tripy/tripy/backend/mlir/memref.py
tripy/tripy/backend/mlir/utils.py

MLIR-TensorRT requires strides for function arguments and results in canonical order.
https://github.com/NVIDIA/TensorRT-Incubator/pull/252 adds a check to validate memref stride against a canonical stride order. In Tripy, memref strides are derived from framework DL Pack tensors. Creating a memref with a non-canonical DL Pack tensor stride throws an exception.
Add a try-catch block to catch such an exception and augment with suggestions on creating a DL Pack tensor with canonical stride for Tripy-supported frameworks.
Add unit tests to create a non-canonical stride tensor to validate exceptions and suggestions.

Add checks for non-canonical strides

---

tripy/pyproject.toml
tripy/tests/frontend/trace/ops/test_unsqueeze.py
tripy/tests/integration/test_reshape.py
tripy/tests/integration/test_unsqueeze.py
tripy/tripy/backend/mlir/utils.py
tripy/tripy/frontend/trace/ops/__init__.py
tripy/tripy/frontend/trace/ops/unsqueeze.py
tripy/tripy/frontend/utils.py

This MR resolves the following:
1. In a trivial example like below, we were earlier computing shape of dynamic shape trace tensor which can become very expensive if reshape occurs somewhere in the middle of a big compute graph. The fix is a simple hack to force the shape of trace tensor when its statically known (in this case it is when we convert a shape scalar to 1d tensor).
```py
a = tp.ones((2, 3, 4))
s1, s2, s3 = a.shape
out = tp.reshape(a, (s1, s2, s3 / 2, 2))
```
2. Fixes #246 (thanks to @yizhuoz004 for the suggested fix)

Fix unnecessary calls to compute shape of trace tensor; fix #246

---

tripy/docs/pre0_user_guides/02-compiler.md
tripy/tests/backend/api/test_compile.py
tripy/tripy/backend/api/compile.py
tripy/tripy/frontend/tensor.py
tripy/tripy/frontend/trace/ops/base.py
tripy/tripy/frontend/trace/ops/storage.py
tripy/tripy/frontend/trace/tensor.py

Updates the `tp.compile` API so that an error is emitted if a tensor is evaluated while tracing for the purposes of compiling.

Updates the compiler to emit errors if evaluating while tracing

---

tripy/tripy/backend/mlir/executor.py
tripy/tripy/backend/mlir/memref.py
tripy/tripy/common/exception.py
tripy/tripy/common/utils.py
tripy/tripy/flat_ir/ops/constant.py
tripy/tripy/frontend/trace/ops/storage.py
tripy/tripy/frontend/trace/ops/utils.py
tripy/tripy/frontend/utils.py
tripy/tripy/utils/stack_info.py

MLIR-TRT includes an assertion that disallows a stream from being provided when creating a host memref. This change adds a new `create_memref` helper which will avoid passing the stream in such cases. This also unifies all the call-sites to use this new helper.

Avoids passing stream when creating host memrefs to not trip an assertion

---

tripy/tests/frontend/test_shape.py
tripy/tests/frontend/test_utils.py
tripy/tripy/frontend/ops/repeat.py
tripy/tripy/frontend/shape.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/utils.py

Addresses issue https://github.com/NVIDIA/TensorRT-Incubator/issues/233, reopened from #265 and incorporating suggestions (thanks, @pranavm-nvidia). Per discussions, there are not many remaining uses of the `convert_inputs_to_tensors` decorator in the codebase and it also seems that in just about all of those cases, it would not make sense to accept both shapes and tensors.

[Tripy] Disallow passing both Shapes and Tensors with the `convert_inputs_to_tensors decorator`

---

mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/test/python/mlir_tensorrt_runtime/test_runtime_debug_dump.py

Allow enabling global llvm::DebugFlag and setting current debug types from runtime python bindings.
Usage:
```
runtime.GlobalDebug.flag = True
runtime.GlobalDebug.set_types(["runtime", "allocator"])
```
Runtime debug dumps:
```
/workspaces/TensorRT-Incubator/mlir-tensorrt/executor/lib/Runtime/API/API.cpp:457 AllocTracker is now tracking 0x5b6000200 size=96 space=device ownership=internal
[runtime] copying 0x00005C9147A03470 to 0x00000005B6000200 size=96 bytes asynchronously via pinned staging buffer at 0x00000005B5000000
/workspaces/TensorRT-Incubator/mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp:133 freeing execution context at 101779074191656
```

[Python/Runtime] Add bindings to enable llvm global debug flag from runtime api

---

tripy/docs/post0_developer_guides/how-to-add-new-ops.md
tripy/tripy/frontend/trace/ops/base.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/cast.py
tripy/tripy/frontend/trace/ops/convolution.py
tripy/tripy/frontend/trace/ops/expand.py
tripy/tripy/frontend/trace/ops/fill.py
tripy/tripy/frontend/trace/ops/gather.py
tripy/tripy/frontend/trace/ops/iota.py
tripy/tripy/frontend/trace/ops/matmul.py
tripy/tripy/frontend/trace/ops/pad.py
tripy/tripy/frontend/trace/ops/permute.py
tripy/tripy/frontend/trace/ops/pooling.py
tripy/tripy/frontend/trace/ops/reduce.py
tripy/tripy/frontend/trace/ops/reshape.py
tripy/tripy/frontend/trace/ops/resize.py
tripy/tripy/frontend/trace/ops/shape.py
tripy/tripy/frontend/trace/ops/slice.py
tripy/tripy/frontend/trace/ops/split.py
tripy/tripy/frontend/trace/ops/storage.py
tripy/tripy/frontend/trace/ops/utils.py
tripy/tripy/frontend/trace/ops/where.py

Partly addresses https://github.com/NVIDIA/TensorRT-Incubator/issues/233, reopened from #266 and incorporating feedback (thanks, @pranavm-nvidia). `infer_shape_output_idx`s is no longer a very descriptive name since it can now distinguish `Shape` outputs and `ShapeScalar` outputs. This PR renames it to `infer_tensor_variants`. Additionally, it changes the format of the return value for that method to use `Shape` and `ShapeScalar` types as outputs directly, avoiding magic string constants.

[Tripy] Rename `infer_shape_output_idxs` to `infer_tensor_variants`

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/StableHloToExecutable.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Dialect/Plan/IR/PlanOps.td
mlir-tensorrt/compiler/include/mlir-tensorrt/Dialect/Plan/Transforms/Passes.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Dialect/Plan/Transforms/Passes.td
mlir-tensorrt/compiler/lib/Dialect/Plan/IR/PlanOps.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/AllocTensors.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/CreateClosedRegions.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/OutlineClusters.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/Passes.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/StablehloClustering.cpp
mlir-tensorrt/test/Dialect/Plan/create-closed-regions.mlir
mlir-tensorrt/test/Dialect/Plan/invalid.mlir
mlir-tensorrt/test/Dialect/Plan/plan-alloc-tensors.mlir
mlir-tensorrt/test/Dialect/Plan/roundtrip.mlir

The Plan dialect has been enhanced to support non-DPS calling conventions, with updates to PlanAllocTensorsPass and CreateClosedRegionsPass. Additionally, the Plan transformation now converts both non-DPS and DPS group operations to CallAllocOp and CallOp respectively, required for subsequent transformations.

[Dialect/Plan] Update Plan dialect to use non-dps calling convention

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Dialect/TensorRTRuntime/IR/TensorRTRuntimeOps.td
mlir-tensorrt/compiler/lib/Conversion/TensorRTRuntimeToExecutor/TensorRTRuntimeToExecutor.cpp
mlir-tensorrt/compiler/lib/Dialect/TensorRTRuntime/IR/TensorRTRuntime.cpp
mlir-tensorrt/compiler/lib/Dialect/TensorRTRuntime/Transforms/BufferizableOpInterfaceImpl.cpp
mlir-tensorrt/test/Conversion/TensorRTRuntimeToExecutor/tensorrt-runtime-to-executor.mlir
mlir-tensorrt/test/Dialect/TensorRTRuntime/invalid.mlir
mlir-tensorrt/test/Dialect/TensorRTRuntime/one-shot-bufferize.mlir
mlir-tensorrt/test/Dialect/TensorRTRuntime/roundtrip.mlir

Extend ConvertTensorRTToTensorRTRuntime to handle both DPS and non-DPS calling styles. Introduce EnqueueAllocOp for non-DPS execution and its conversion to executor CallOp.

[Dialect/TensorRTRuntime] Update tensorrt runtime dialect to use non-dps calling convention

---

mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/Passes.cpp
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRT.cpp
mlir-tensorrt/tensorrt/test/Dialect/TensorRT/canonicalize.mlir

Adds canonicalizer for resize ops to absorb cast ops which cast from more specifics types into dynamic types.

[tensorrt] Add canonicalizer for resize to absorb generalizing casts

---

tripy/docs/conf.py
tripy/docs/post0_developer_guides/how-to-add-new-ops.md
tripy/tests/constraints/object_builders.py
tripy/tests/constraints/test_dtypes.py
tripy/tests/frontend/test_shape.py
tripy/tests/frontend/test_utils.py
tripy/tests/frontend/trace/ops/test_dequantize.py
tripy/tests/frontend/trace/ops/test_quantize.py
tripy/tests/integration/test_quantize.py
tripy/tests/test_function_registry.py
tripy/tripy/common/exception.py
tripy/tripy/constraints.py
tripy/tripy/frontend/ops/allclose.py
tripy/tripy/frontend/trace/ops/binary_elementwise.py
tripy/tripy/frontend/trace/ops/dequantize.py
tripy/tripy/frontend/trace/ops/quantize.py
tripy/tripy/frontend/trace/ops/slice.py
tripy/tripy/frontend/utils.py
tripy/tripy/types.py
tripy/tripy/utils/result.py

- Replaces `convert_inputs_to_tensors` decorator with `convert_to_tensors`,
which will convert any `TensorLike` arguments by default and sync data types
according to any specified data type constraints. This means that information
does not need to be duplicated in the decorator like it used to be.
- Disallows unsafe downcasting in the new `convert_to_tensors` decorator.
Previously, you could have:
```py
x = tp.Tensor([1], dtype=tp.int32)
x * 3.99
```
which would yield a result equal to:
```py
tp.Tensor([3])
```
due to truncation when casting.
- Fixes several type annotations for binary elementwise ops.
- Removes NestedNumberSequence
We only want to convert Python numbers to Tensors automatically.
It doesn't make sense to write, for example, `x + [3]`.

Replaces `convert_inputs_to_tensors` decorator with a better decorator

---

mlir-tensorrt/compiler/lib/Conversion/TensorRTToTensorRTRuntime/TensorRTToTensorRTRuntime.cpp
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRT.cpp
mlir-tensorrt/test/Conversion/TensorRTToTensorRTRuntime/tensorrt-to-tensorrt-runtime.mlir

Add non-DPS variant of `tensorrt::CallOp` i.e. `tensorrt::CallAllocOp`. Add conversion from call alloc op to runtime dialect enqueue alloc op.

[Dialect/TensorRT] Update tensorrrt dialect to use non-dps calling convention

---

mlir-tensorrt/CMakeLists.txt
mlir-tensorrt/CMakePresets.json
mlir-tensorrt/README.md

This change adds a CMake presets file to MLIR-TensorRT, which helps to
simplify the initial CMake setup considerably.
The build documentation is updated to use this feature, and some additional
notes are added to describe how to control the TensorRT version that
is used for build & test.

NFC: Add MLIR-TensorRT 'CMakePresets.json' and update build documentation

---

mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/CMakeLists.txt
mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp

`IOutputAllocator` needs to be supported for both TRT 9.2 and TRT 10.x release. Add support for using TRT 9.2 API.

Update IOutputAllocator usage to be compatible with TensorRT 9.2 APIs

---

tripy/tests/README.md
tripy/tests/backend/api/test_stream.py
tripy/tests/common/test_utils.py
tripy/tests/constraints/object_builders.py
tripy/tests/constraints/test_dtypes.py
tripy/tests/frontend/trace/ops/test_iota.py
tripy/tests/integration/test_plugin.py
tripy/tripy/backend/mlir/utils.py
tripy/tripy/flat_ir/flat_ir.py
tripy/tripy/frontend/ops/cumsum.py
tripy/tripy/frontend/ops/repeat.py
tripy/tripy/frontend/trace/ops/convolution.py
tripy/tripy/frontend/trace/ops/iota.py
tripy/tripy/frontend/trace/ops/utils.py
tripy/tripy/frontend/utils.py
tripy/tripy/utils/ast.py
tripy/tripy/utils/utils.py

- Updates plugin test to check for shapes
- Makes process_dim a regular function instead of a decorator. Making `process_dim` a decorator is overkill and complicates the stack infomation unnecessarily. This change makes it a regular function so that it can be used more broadly.
- Removes dead code
- Fixes a typo in the profiling section of the README
- Makes datatype constraints tests significantly faster by not evaluating inputs.

Miscellaneous fixes

---

.github/workflows/mlir-tensorrt-ci.yml
mlir-tensorrt/build_tools/cmake/Dependencies.cmake

This PR makes the following changes in mlir-tensorrt CI,
- Add testing for TensorRT versions 8.6.1.6 and 9.2.
- Add testing with ASAN enabled

[CI] Add more configurations to mlir-tensorrt CI

---

mlir-tensorrt/tensorrt/lib/Target/TensorRTEncodingOpInterface/NetworkEncoder.cpp
mlir-tensorrt/tensorrt/test/Target/TensorRT/linspace.mlir

This PR fixes an issue in linspace op conversion which was failing if output of linspace op is dynamic. With this change, if dynamic shape input is provided, IFillLayer is initialized with empty dims first and later dimensions are set to dynamic shape tensor.
Fixes https://github.com/NVIDIA/TensorRT-Incubator/issues/320

[mlir-tensorrt][tensorrt] Fix an issue in linspace op conversion

---

tripy/tests/backend/api/test_compile.py
tripy/tests/common/test_exception.py
tripy/tests/helper.py
tripy/tripy/common/exception.py
tripy/tripy/frontend/module/module.py
tripy/tripy/frontend/tensor.py
tripy/tripy/logging/logger.py
tripy/tripy/utils/ast.py

In the case where a tensor is evaluated while compiling and then used in the computation graph, we throw an error. However, there are cases where the result of evaluation could make a round-trip through non-Tripy code, in which case we lose visibility. An example of this, assuming `a` and `b` are tensors, is:
```py
b = b + int(a.shape[0])
```
Here, `a.shape[0]` will be evaluated due to the `int` conversion and then used by the add operation with `b`. Because it was a Python integer in between, Tripy has no way to track that it actually came from an evaluated tensor.
Hence, this change prints warnings in these ambiguous cases when a tensor is evaluated while compiling. Here's an example of the warning messages:
```
[W] Tensor was evaluated while compiling which may cause unexpected …
```

Adds a warning if a tensor is evaluated while compiling

---

.github/workflows/tripy-l1.yml
.github/workflows/tripy-release.yml
tripy/README.md
tripy/RELEASE.md
tripy/docs/packages.html
tripy/pyproject.toml
tripy/tests/helper.py
tripy/tests/test_packaging.py
tripy/tripy/__init__.py

Adds a release packaging pipeline which will build and deploy the documentation
and push wheels to a GitHub release when a matching tag is pushed.
This change also updates L1 to no longer push documentation. This ensures that
the published documentation is always aligned with the latest wheel.

Adds release packaging pipeline and updates version to 0.0.3

---

.github/workflows/tripy-release.yml
tripy/pyproject.toml

Pins versions for packages required to build wheels to the correct versions. Older versions do not build the package correctly (missing files and metadata).

Pins versions for release pipeline dependencies

---

tripy/README.md
tripy/docs/generate_rsts.py
tripy/docs/post0_developer_guides/debugging.md
tripy/docs/post0_developer_guides/design-decisions.md
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/docs/pre0_user_guides/01-quantization.md
tripy/examples/nanogpt/README.md
tripy/examples/nanogpt/example.py
tripy/examples/nanogpt/model.py
tripy/examples/nanogpt/quantization.py
tripy/examples/nanogpt/requirements.txt
tripy/tests/frontend/module/test_linear.py
tripy/tests/helper.py
tripy/tests/integration/test_groupnorm.py
tripy/tests/integration/test_layernorm.py
tripy/tests/test_packaging.py
tripy/tripy/frontend/module/linear.py
tripy/tripy/frontend/module/module.py
tripy/tripy/frontend/module/parameter.py

[Enables execution of shell blocks during documentation generation](https://github.com/NVIDIA/TensorRT-Incubator/commit/c7efe46185bcde15839b56c2b235ff075992b592)
Updates our documentation generation logic to allow execution of shell
blocks in guides and READMEs. This allows us to ensure that the content
of shell blocks is always functional.
Consequently, we also remove the packaging test that was previously used
as a proxy for running the packaging instructions in the README.
[Adds support for default parameters with unknown shapes, fixes linear](https://github.com/NVIDIA/TensorRT-Incubator/commit/e981b8bece25ed5d6d1966b61e94e64641cf22cf)
Updates `DefaultParameter` to allow unknown shapes. In such cases, we will
allow the member to be set to a parameter with any shape but a matching data …

Fixes nanogpt, various other fixes

---

.github/workflows/post-merge-package-index-update.yml
tripy/docs/packages.html

When we want to update to a new release of MLIR-TRT, we first need to publish `packages.html` so we are able to `pip install` correctly. Previously, we were doing this in each nightly, but it's better to do so whenever we push a change to `packages.html` on `main`. That's what this workflow does.

Adds a new workflow to update package index

---

tripy/README.md
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/docs/pre0_user_guides/02-compiler.md
tripy/examples/nanogpt/README.md
tripy/tests/backend/api/test_executable.py
tripy/tests/test_examples.py
tripy/tripy/backend/api/compile.py
tripy/tripy/backend/api/executable.py
tripy/tripy/backend/api/input_info.py

- Improves the introduction, compiler, and quickstart guides
- Fixes various docstrings
- Removes `Executable.get_input_info()` and `Executable.get_output_info()` because they weren't returning complete information (e.g. names missing). We should flesh out the API before making it publicly visible.

Improves various guides, hides incomplete Executable APIs

---

mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/MaterializeShapeCalculations.cpp
mlir-tensorrt/executor/test/Unit/CMakeLists.txt
mlir-tensorrt/test/Dialect/Plan/materialize-shape-calculations.mlir

Prior to this change, the 'plan-materialize-shape-calculations' pass could perform
a number of simplifications based on bounds analysis, but it did not actually
perform StableHLO simplifications. This change adds additional
`stablehlo-canonicalize-dynamism` patterns so that the IR can be further simplified.

Move internal changes

---

tripy/README.md
tripy/docs/_static/style.css
tripy/tests/test_function_registry.py
tripy/tripy/backend/api/executable.py
tripy/tripy/frontend/ops/tensor_initializers.py
tripy/tripy/function_registry.py

[Updates README to include links to common guides](https://github.com/NVIDIA/TensorRT-Incubator/commit/359f5089778edb476857cc017a036b6f891ec891)
[Improves docstrings for overloaded functions](https://github.com/NVIDIA/TensorRT-Incubator/commit/745f4586e60ee9967bab0cccf91b99cec84fb4f4)
Improves the docstrings for overloaded functions to be stylistically similar
to non-overloaded functions.
Also updates the helpers that generate strings from type annotations to be
more consistent with the style the documentation uses. For example, `Union[int, float]`
will now be rendered as `int | float`.

Improves docstrings for overloaded functions, updates README

---

tripy/examples/nanogpt/README.md
tripy/examples/nanogpt/example.py
tripy/tests/test_examples.py

Note: top K helps stablize the result a bit but not much, the result of `int8-weight-only` can vary among several outputs on CI machine, but cannot be reproduced locally. Worth looking into this issue later on.

Change topK to 10 in nanoGPT sample

---

mlir-tensorrt/tensorrt/lib/TensorRT/Transforms/TransposeElimination.cpp
mlir-tensorrt/tensorrt/test/Dialect/TensorRT/transpose-elimination.mlir

Fixes an issue where the `tensorrt-transpose-elimination` pass did not correctly
calculate cost for tensors that are dynamically shaped. After this change,
the pass now considers any dynamically shaped tensor to have maximum cost;
better heuristics would require that we move transpose elimination higher
in the pipeline (e.g. to Plan dialect where we might have better information
about shapes).
Fixes issue #368 
GitOrigin-RevId: 99e6260ee0c2679e1e6539e60b7840d9a90845b9

[tensorrt] Fix handling of dynamic shapes in `tensorrt-transpose-elimination`

---

mlir-tensorrt/compiler/lib/Dialect/StableHloExt/Transforms/ConstantFolding.cpp
mlir-tensorrt/test/Dialect/StableHloExt/constant-folding.mlir

Our next LLVM & StableHLO upgrade will incorporate some additional simplification
patterns. However, the upgrade is large and will not fully land until mid
next week.
Until then, incorporate some critical concat and slice simplification patterns
that simplify shape calculation IR. Solves https://github.com/NVIDIA/TensorRT-Incubator/issues/381.
GitOrigin-RevId: 2a875a35547b89c96d530878907312a0f898e508

[compiler/StableHloExt] Incorporate some simplification patterns from upstream StableHLO

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Dialect/StableHloExt/Transforms/Passes.td
mlir-tensorrt/test/Dialect/StableHloExt/refine-shapes.mlir

Increases the max number of iterations that the initial dynamic shape refinement
pipeline will iterate in order to better reported use cases.

[compiler/StableHloExt] Bump max iterations in `stablehlo-ext-refine-shapes`

---

mlir-tensorrt/compiler/lib/CAPI/Compiler/Compiler.cpp

Fixes an issue where the `mtrtCompilerClientDestroy` function was not correctly
destroying the underlying C++ CompilerClient object.
GitOrigin-RevId: 39362fcb2fc2bf8233b4695fed5e6a3944cdf606

[compiler]  Fix CompilerClient CAPI destroy function

---

tripy/RELEASE.md
tripy/docs/conf.py
tripy/docs/generate_rsts.py
tripy/docs/post0_developer_guides/architecture.md
tripy/docs/post0_developer_guides/debugging.md
tripy/docs/post0_developer_guides/how-to-add-new-ops.md
tripy/pyproject.toml
tripy/tests/README.md
tripy/tests/helper.py
tripy/tests/test_examples.py
tripy/tests/test_helper.py
tripy/tests/test_internal_docs.py
tripy/tests/test_ux.py
tripy/tripy/backend/api/compile.py
tripy/tripy/frontend/trace/ops/plugin.py

This change updates our documentation generation to format all code blocks
with `black`. This helps ensure that lines do not overflow and create scrollable
elements in the rendered docs. For lines that `black` doesn't touch (e.g. comments),
we include our own assertions to ensure they don't exceed the length limits.
The logic to extract code from a code block (i.e. stripping out markup) has also
been consolidated.
Finally, this change removes the `manual` test cadence and related tests since
they were redundant (the same things are tested during doc generation) and didn't
add any value (the thought was they would make it easier to debug, but (1) they don't
and (2) it's rarely difficult to figure out what's wrong with the code blocks in documentation)

Formats code in documentation with black

---

mlir-tensorrt/CMakeLists.txt
mlir-tensorrt/build_tools/stablehlo_aggressive_folder.patch

This PR provides a patch to fix two issues in StableHlo
upstream,
- If some op is constant folded and op users are certain
stablehlo ops (which don't allow different type for operand
and result) OR ops with different dialect, `tensor.cast`
should be inserted.
MLIR-TensorRT constant folding pass does this but upstream
stablehlo pass doesn't do this, causing error. Some
logic from MLIR-TRT is patched into upstream.
- Upstream `ReshapeOpCanon` pattern to simplify
`stablehlo.reshape` op failed if input to reshape
is `DenseResourceElementsAttr`. This is fixed.
- Many patterns where replacing op with a new op,
without giving consideration to casting. This is 
fixed.
Solves: https://github.com/NVIDIA/TensorRT-Incubator/issues/378

Fix stablehlo constant folding bugs through patch

---

mlir-tensorrt/compiler/lib/Conversion/StablehloToTensorRT/StablehloToTensorRT.cpp
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRT.cpp
mlir-tensorrt/test/Conversion/StablehloToTensorRT/stablehlo-to-tensorrt.mlir

This PR fixes an issue in `stablehlo.slice` conversion which popped when result type is dynamic.
In the converter, we use `tensorrt.slice` op builder that infers result based on `static_size` (output shape is same as size on TensorRT side) and `size` was taken as shape of stablehlo op output. This caused two issues,
- `truncateI64ToI32` failed for dynamic output because dynamic dim can't be truncated to i32 without loss.
- A new builder needed which could set result to dynamic shape even when size is static.
With this change,
- `size` is computed as `ceil(limit-start)/stride` (these are stablehlo slice op attributes) and NOT as shape of output.
- A new builder is added.
MLIR test is added.

[compiler][conversion] Fix an issue in `stablehlo.slice` conversion

---

mlir-tensorrt/compiler/include/mlir-tensorrt-c/Compiler/Compiler.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/OptionsRegistry.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/StableHloToExecutable.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Registration/RegisterMlirTensorRtPasses.h
mlir-tensorrt/compiler/lib/CAPI/Compiler/Compiler.cpp
mlir-tensorrt/compiler/lib/Compiler/CMakeLists.txt
mlir-tensorrt/compiler/lib/Compiler/OptionsRegistry.cpp
mlir-tensorrt/compiler/lib/Compiler/StableHloToExecutable.cpp
mlir-tensorrt/python/bindings/Compiler/CompilerPyBind.cpp
mlir-tensorrt/python/bindings/Utils.h
mlir-tensorrt/test/python/mlir_tensorrt_compiler/compiler_api/test_options_context.py

In order to support more than just the StableHloToExecutable pipeline, we need to be able to create different option types from the API. This commit exposes the base `OptionsContext` class in the Python API and includes a mechanism for child classes to register themselves with the client, allowing them to be created through a common API.

Exposes base `OptionsContext` class in the API

---

tripy/docs/README.md
tripy/docs/conf.py
tripy/docs/pre0_user_guides/01-quantization.md
tripy/examples/nanogpt/weight_loader.py
tripy/tests/frontend/module/conftest.py
tripy/tests/frontend/module/test_linear.py
tripy/tests/frontend/module/test_module.py
tripy/tests/frontend/module/test_parameter.py
tripy/tests/frontend/module/test_sequential.py
tripy/tests/helper.py
tripy/tests/integration/test_batchnorm.py
tripy/tests/integration/test_groupnorm.py
tripy/tests/integration/test_layernorm.py
tripy/tests/integration/test_linear.py
tripy/tests/integration/test_sequential.py
tripy/tests/performance/cases/linear_block.py
tripy/tests/performance/test_perf.py
tripy/tripy/frontend/module/__init__.py
tripy/tripy/frontend/module/batchnorm.py
tripy/tripy/frontend/module/conv.py
tripy/tripy/frontend/module/conv_transpose.py
tripy/tripy/frontend/module/embedding.py
tripy/tripy/frontend/module/groupnorm.py
tripy/tripy/frontend/module/layernorm.py
tripy/tripy/frontend/module/linear.py
tripy/tripy/frontend/module/module.py
tripy/tripy/frontend/module/parameter.py

Removes the Parameter API which was used to denote constants in computation graphs. We can instead use regular `Tensor`s since anything not specified as an input to the compile call is treated as a constant.
`DefaultParameter` is preserved as an internal implementation detail for efficiently defining expected parameter shapes/dtypes without materializing data.

Removes Parameter API

---

tripy/tests/backend/api/test_compile.py
tripy/tests/backend/api/test_input_info.py
tripy/tests/helper.py
tripy/tests/integration/test_conv_transpose.py
tripy/tests/integration/test_sequential.py
tripy/tripy/backend/api/input_info.py
tripy/tripy/common/shape_bounds.py
tripy/tripy/frontend/ops/repeat.py
tripy/tripy/types.py

Introduces a new `IntLike` type alias that covers integers and `DimensionSize`s and updates `InputInfo` to accept shape arguments of this new type. Note that the `DimensionSize`s must be evaluated in order to populate the profile correctly.
This allows for using the shapes of eager mode tensors when compiling.

Allows `DimensionSize`s to be used in `InputInfo`

---

.github/workflows/mlir-tensorrt-ci.yml
mlir-tensorrt/CMakeLists.txt
mlir-tensorrt/build_tools/patches/stablehlo/0002-Fix-a-couple-missing-checks-for-static-shapes-in-sta.patch
mlir-tensorrt/build_tools/scripts/cicd_build.sh
mlir-tensorrt/compiler/lib/Conversion/TensorRTToTensorRTRuntime/CMakeLists.txt
mlir-tensorrt/test/Dialect/Plan/segmentation-pipeline.mlir
mlir-tensorrt/test/python/mlir_tensorrt_compiler/compiler_api/test_options_context.py

Added a patch that was missing from the last StableHLO upgrade. This patch
addresses some issues mentioned in https://github.com/openxla/stablehlo/issues/2634.
An additional test is added to mlir-tensorrt as a regression test.

[mlir-tensorrt] Add additional missing StableHLO patch

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/Client.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/StableHloToExecutable.h
mlir-tensorrt/compiler/lib/CAPI/Compiler/Compiler.cpp
mlir-tensorrt/compiler/lib/Compiler/StableHloToExecutable.cpp
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/Utils/OptionsBundle.h

Introduces an `OptionsBundle` class that will make it easier to share groups of
options across different options classes. This class essentially allows you to bundle
together option providers like `DebugOptions` so that they don't need to be managed
individually.

Adds an OptionsBundle class to allow options classes to subscribe to option groups

---

.github/workflows/tripy-l0.yml
.github/workflows/tripy-l1.yml
tripy/docs/pre0_user_guides/02-compiler.md
tripy/examples/nanogpt/example.py
tripy/examples/nanogpt/model.py
tripy/examples/nanogpt/weight_loader.py
tripy/tests/backend/api/test_input_info.py
tripy/tests/frontend/module/test_module.py
tripy/tests/helper.py
tripy/tests/test_function_registry.py
tripy/tripy/backend/api/compile.py
tripy/tripy/backend/api/executable.py
tripy/tripy/backend/api/input_info.py
tripy/tripy/frontend/module/layernorm.py
tripy/tripy/frontend/module/sequential.py
tripy/tripy/frontend/trace/ops/pooling.py
tripy/tripy/frontend/trace/ops/squeeze.py
tripy/tripy/function_registry.py

[Adds support for various types in our type checking logic](https://github.com/NVIDIA/TensorRT-Incubator/commit/3c95dafa9e4c21c8fab6ab7e2e83ecb98c664b83)
Adds support for dictionaries, tuple, and callables in our type checking.
Also removes a fallback path where we would skip type checking if we weren't
able to handle an annotation. Since we're only doing type checking on Tripy APIs,
where we control the type annotations, we should not have this fallback path but
should instead add support for whatever types we use.
Also updates various parts of the code to respect type annotations. Many of these
were working before since the type annotation would just be ignored.
[Updates pipelines to remove mentions of the "manual" test cadence](https://github.com/NVIDIA/TensorRT-Incubator/commit/f9d2d9b …

Fixes type checking, nanoGPT

---

.github/workflows/mlir-tensorrt-ci.yml
mlir-tensorrt/README.md

- Removes downloaded TRT binaries from the caching paths.
- Includes some NFC documentation changes to test the effects.

[mlir-tensorrt] NFC: update GitHub actions caching config for MLIR-TRT jobs

---

.github/workflows/tripy-l1.yml
.github/workflows/tripy-release.yml
tripy/examples/nanogpt/README.md
tripy/examples/segment-anything-model-v2/README.md
tripy/pyproject.toml
tripy/tests/README.md
tripy/tests/frontend/test_tensor.py
tripy/tests/helper.py
tripy/tests/test_examples.py
tripy/tests/test_notebooks.py
tripy/tripy/frontend/tensor.py

- Adds an explicit `pytest` test for the notebooks so that it works just like any other test.
- Adds a new `l1_release_package` cadence which will run a test using the release package instead of TOT.
- Updates the release pipeline to run testing before pushing the release.
- Updates the L1 pipeline to run the `l1_release_package` tests.
- Fixes a bug in the documentation where expected errors would not be displayed

Adds explicit notebook tests, updates CI

---

.github/workflows/tripy-l0.yml
.github/workflows/tripy-update-benchmark.yml
tripy/CONTRIBUTING.md
tripy/nvtripy/__init__.py
tripy/pyproject.toml

[Updates contributing guide to point to rendered documentation](https://github.com/NVIDIA/TensorRT-Incubator/commit/b0df1d1a6eddfa3b591a7b124c5e6f0a3ad8fb4c)
[Updates version to 0.0.8](https://github.com/NVIDIA/TensorRT-Incubator/commit/aa12cfe11f47367c828c75821e5f708b57774604)
[Updates L0 to store benchmark results in a post-merge pipeline](https://github.com/NVIDIA/TensorRT-Incubator/commit/52ade530667e4462dffdcaeb8e4c848015d0941f)
By performing the upload of benchmark results in a post-merge pipeline, we
can enable contributions from forks, which don't otherwise have permission
to push new benchmark results.

Enable contributions from external sources

---

mlir-tensorrt/compiler/include/mlir-tensorrt-c/Compiler/Compiler.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/Client.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/OptionsProviders.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/OptionsRegistry.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/StableHloToExecutable.h
mlir-tensorrt/compiler/lib/CAPI/Compiler/Compiler.cpp
mlir-tensorrt/compiler/lib/Compiler/Client.cpp
mlir-tensorrt/compiler/lib/Compiler/OptionsRegistry.cpp
mlir-tensorrt/compiler/lib/Compiler/StableHloToExecutable.cpp
mlir-tensorrt/compiler/test/python/mlir_tensorrt_compiler/compiler_api/test_executor_translation.py
mlir-tensorrt/executor/include/mlir-executor-c/Target/ExecutorTranslations.h
mlir-tensorrt/executor/lib/CAPI/CMakeLists.txt
mlir-tensorrt/executor/lib/CAPI/Target/CMakeLists.txt
mlir-tensorrt/executor/lib/CAPI/Target/ExecutorTranslations.cpp
mlir-tensorrt/python/CompilerPackage.cmake
mlir-tensorrt/python/bindings/Compiler/CompilerPyBind.cpp
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/Utils/Options.h
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/Utils/OptionsBundle.h
mlir-tensorrt/tensorrt/lib/Target/TranslateToTensorRT.cpp
mlir-tensorrt/tensorrt/lib/Utils/Options.cpp

This change adds a CompilationTask (cached pass managers) registry
which enables creating and looking up cached compilation tasks from
the Python API by just passing a mnemonic task name and a list of
string options.
GitOrigin-RevId: f19e634e8ff8338809fe2c1b8efa730ef2e14f21

Move internal change: [compiler] Add compilation task registry

---

.github/workflows/tripy-l0.yml
tripy/README.md
tripy/docs/_templates/layout.html
tripy/docs/conf.py
tripy/docs/generate_rsts.py
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/tests/helper.py

[Refactors main README and introduction guide](https://github.com/NVIDIA/TensorRT-Incubator/pull/471/commits/2f88ae2d1f64a7a68eacea6b9cfefbdc0690bad3)
- Refactors documentation to be significantly less verbose
[Excludes table-of-contents from main page](https://github.com/NVIDIA/TensorRT-Incubator/pull/471/commits/96ffc9e4c55b72092f72665ac1de0aa2af82c45e)
- Removes the table of contents at the end of the main page since it is always
visible in the side bar.

Refactors some guides

---

tripy/README.md
tripy/docs/generate_rsts.py
tripy/docs/post0_developer_guides/debugging.md
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/nvtripy/config.py
tripy/nvtripy/frontend/cache.py
tripy/tests/frontend/test_cache.py
tripy/tests/helper.py

[Adds a marker to disable printing locals](https://github.com/NVIDIA/TensorRT-Incubator/commit/56b0af44b0aec505acd067c1db9e1382df3e3398)
Adds a `doc: no_print_locals` markdown marker in cases where we can't
use inline comments (e.g. where the raw markdown is user-visible, like in the
main README).
[Updates documentation and naming for option to enable eager mode cache](https://github.com/NVIDIA/TensorRT-Incubator/commit/4f9ea4a2c71cdd455f191811f9e63fca9ae70544)

Minor docstring fixes

---

tripy/README.md
tripy/docs/README.md
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/nvtripy/types.py
tripy/tests/README.md

[Rewrites docs/README.md to be briefer](https://github.com/NVIDIA/TensorRT-Incubator/commit/ab47abea81631269b55f81ca8d67285c8f6ecc5b)
[Rewrites tests/README.md to be briefer](https://github.com/NVIDIA/TensorRT-Incubator/commit/64a65b36d4a4da060a81352c6e2a3745a832e783)
[Various minor changes to public documentation](https://github.com/NVIDIA/TensorRT-Incubator/commit/5a473e8298302f155986ce6afaf3ae8e15aff371)

More documentation refactoring

---

tripy/docs/README.md
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/docs/pre0_user_guides/01-quantization.md
tripy/docs/pre0_user_guides/02-compiler.md
tripy/examples/nanogpt/requirements.txt
tripy/nvtripy/backend/mlir/memref.py
tripy/nvtripy/frontend/trace/ops/shape.py
tripy/nvtripy/frontend/utils.py
tripy/pyproject.toml
tripy/tests/helper.py
tripy/tests/integration/test_sequential.py

[Refactors quantization guide](https://github.com/NVIDIA/TensorRT-Incubator/pull/480/commits/a62af1053a712cd5066becc130f34b6bf5f1d980)
- Refactors quantization guide to be more concise
- Updates `nvidia-modelopt` version so we don't need a special package index
- Reduces threshold for summary mode when pretty printing tensors.
- Adds a `# doc: no-output` tag to omit output from code examples.

Refactors quantization guide 

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Dialect/Plan/Transforms/Passes.td
mlir-tensorrt/compiler/lib/Compiler/StablehloToExecutable/StablehloToExecutable.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/CMakeLists.txt
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/CreateClosedRegions.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/Passes.cpp
mlir-tensorrt/compiler/lib/Dialect/Plan/Transforms/StablehloClustering.cpp
mlir-tensorrt/compiler/test/Dialect/Plan/create-closed-regions.mlir
mlir-tensorrt/compiler/test/python/IntegrationTests/test_non_dps_cconv.py
mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h
mlir-tensorrt/executor/include/mlir-executor/Runtime/API/API.h
mlir-tensorrt/executor/include/mlir-executor/Support/Allocators.h
mlir-tensorrt/executor/lib/CAPI/Common/Common.cpp
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/executor/lib/Runtime/API/API.cpp
mlir-tensorrt/executor/lib/Runtime/Backend/Lua/LuaRuntime.cpp
mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/CUDA/CUDAModule.cpp
mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp
mlir-tensorrt/executor/lib/Support/Allocators.cpp
mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/tensorrt/lib/Target/TensorRTEncodingOpInterface/NetworkEncoder.cpp

Implement python binding changes to allow execute function return multiple returns. Update tests to use non-DPS style calling convention.
Also, enable end to end lowering by enabling conversion of closed alloc group op to tensorrt dialect.
Miscellaneous fixes:
1. Add missing handling of `CallAllocOp` in EliminateShapeOps pass.
2. Skip non ranked tensor type function arguments while collecting host tensor arguments.
3. Temporarily add a pass to remove clone operation in MemRefToExecutor dialect conversion.
4. Relax memref creation for empty shape tensors.
5. Fix memref life returned from Lua function results. This required session allocator to track returned memref.
Also, address
Fix incorrect indexing into output memref results
Return error status instead of silently erroring out during …

Enable end to end DPS testing

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/TensorRTToExecutable/TensorRTToExecutable.h
mlir-tensorrt/compiler/lib/Compiler/TensorRTToExecutable/TensorRTToExecutable.cpp
mlir-tensorrt/compiler/test/python/IntegrationTests/test_tensorrt_add.py

Add force-entrypoints-return-allocs option to TRT task, also update the integration test to use non-DPS style calling convention.

[Compiler] Add force-entrypoints-return-allocs option to TRT task

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/OptionsProviders.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/StablehloToExecutable/StablehloToExecutable.h
mlir-tensorrt/compiler/include/mlir-tensorrt/Compiler/TensorRTToExecutable/TensorRTToExecutable.h
mlir-tensorrt/compiler/lib/Compiler/StablehloToExecutable/StablehloToExecutable.cpp
mlir-tensorrt/compiler/lib/Compiler/TensorRTToExecutable/TensorRTToExecutable.cpp

Also corrects pass ordering in TensorRTToExecutable.

Moves `force-entrypoints-return-allocs` into a `PlanAllocOptions`

---

tripy/nvtripy/frontend/dimension_size.py
tripy/nvtripy/frontend/ops/cast.py
tripy/nvtripy/frontend/ops/shape.py
tripy/nvtripy/frontend/ops/utils.py
tripy/nvtripy/frontend/tensor.py
tripy/nvtripy/trace/ops/base.py
tripy/nvtripy/trace/ops/cast.py
tripy/nvtripy/trace/ops/constant.py
tripy/nvtripy/trace/ops/shape.py
tripy/nvtripy/trace/tensor.py

[Ports the cast operation to the TRT dialect](https://github.com/NVIDIA/TensorRT-Incubator/commit/ecad27e9dd196c3a7ad7a7898fc6fc9fd361d9c1)
[Ports shape operation to TRT dialect](https://github.com/NVIDIA/TensorRT-Incubator/commit/6340a21de921bc12f7b31cf857394cbf6746685b)
Also adds an optimization for eager mode where the output of `Shape` will
be stored if we evaluate a `GetDimensionSize` so that subsequent `GetDimensionSize`s
do not need to evaluate the entire graph - otherwise, we recompile the graph
once per dimension of the shape.

Ports `cast` and `shape` operations

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/test/Dialect/TensorRT/quantization.mlir

Changes same-shape constraint for QDQ ops to same-rank, so that we can generate output result type with unknown dims.

[TensorRT] Relax same-shape constraint for TRT QDQ ops

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TypeInferenceInterfaceImpls.cpp
mlir-tensorrt/tensorrt/test/Dialect/TensorRT/invalid.mlir

Adds type inference for tensorrt QDQ ops to ensure static dims of input/output types are the same.

[TensorRT] Add type inference for QDQ ops

---

tripy/nvtripy/backend/api/compile.py
tripy/nvtripy/frontend/cache.py
tripy/nvtripy/frontend/tensor.py

We were getting cache misses because the trace could sometimes change (e.g. with shape information) between the `get` and `set` calls. This change merges the two operations into a single `compile` interface.

Fixes cache misses in eager mode cache

---

mlir-tensorrt/tensorrt/lib/Target/TensorRTEncodingOpInterface/NetworkEncoder.cpp
mlir-tensorrt/tensorrt/lib/TensorRT/IR/Verification.cpp

Fixes dynamic linspace translation by passing a 1-D static shape tensor. Relaxes linspace op's verifier when the input step dimension is unknown.

[TensorRT] Fix dynamic linspace translation, relax dynamic verifier

---

mlir-tensorrt/tensorrt/test/Dialect/TensorRT/invalid.mlir

Adds a unit test to check if error is reported when step dim[0] is not equal to rank of output in tensorrt.linspace.

[NFC] Add a negative unit test for dynamic tensorrt.linspace

---

mlir-tensorrt/compiler/lib/Conversion/TensorRTRuntimeToExecutor/TensorRTRuntimeToExecutor.cpp
mlir-tensorrt/compiler/test/Conversion/TensorRTRuntimeToExecutor/tensorrt-runtime-to-executor.mlir
mlir-tensorrt/compiler/test/python/mlir_tensorrt_runtime/test_create_memref.py
mlir-tensorrt/executor/include/mlir-executor/Runtime/API/API.h
mlir-tensorrt/executor/include/mlir-executor/Support/Status.h
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/executor/lib/Runtime/API/API.cpp
mlir-tensorrt/executor/lib/Runtime/Backend/Lua/LuaRuntime.cpp

Summary:
- Restore querying of `rankOffset` from the output descriptor, which was inadvertently removed in a previous merge. Update the related test `tensorrt-runtime-to-executor.mlir`.
- Enhance debugging logs to provide clearer error messages.
- Revert `Allocator::track` to its previous implementation for cases where the incoming pointer is not managed internally by `Allocator`.
- Modify `Allocator::track` to correctly handle cases where an incoming pointer is already managed internally. This adjustment is necessary as `Allocator` now tracks pointers internally when they are returned as function results.
- Refine `Allocator::safeDeallocate` to ensure it only releases pointers that are managed internally.
- Correct a typo in `Allocator::safeDeallocate` for `PointerType::pinned_host`, …

[Allocator] Fix OOM issues in non-DPS mode

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRTVersionCompatibility.cpp
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TypeInferenceInterfaceImpls.cpp
mlir-tensorrt/tensorrt/test/Target/TensorRT/cast.mlir

Adds a `cast` operation to the `tensorrt` dialect. Unlike `identity`, `cast` supports many more combinations of input/output types.

Adds `cast` to `tensorrt` dialect

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRTVersionCompatibility.cpp
mlir-tensorrt/tensorrt/test/Target/TensorRT/shape.mlir

Updates `tensorrt.shape` to allow accepting I64 input tensors. The shape operation doesn't really care about the data type of its input (only shape) and so all data types are supported.

Allows I64 tensors in `tensorrt.shape`

---

mlir-tensorrt/CMakePresets.json
mlir-tensorrt/build_tools/scripts/build_wheels.sh
mlir-tensorrt/python/requirements-dev.txt

This PR adds cmake preset for clang python wheel release and updates `build_wheels.sh` script to use this preset.

[build_tools] Add cmake preset for clang python wheel release

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td
mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRTVersionCompatibility.cpp
mlir-tensorrt/tensorrt/test/Target/TensorRT/TRT10/pooling.mlir

The pooling layer in TRT supports all activation types, which includes BF16. For now, this change is restricted to TRT 10+, but likely would apply to TRT 9 as well.

Enables BF16 in pooling

---

mlir-tensorrt/tensorrt/test/Target/TensorRT/TRT10/shape.mlir
mlir-tensorrt/tensorrt/test/Target/TensorRT/shape.mlir

I64 is not supported on older versions of TRT, so this change moves the I64 shape test to the TRT10 directory.

Moves I64 shape test to TRT10 directory

---

mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRTVersionCompatibility.cpp
mlir-tensorrt/tensorrt/lib/TensorRT/IR/Verification.cpp
mlir-tensorrt/tensorrt/test/Dialect/TensorRT/invalid.mlir
mlir-tensorrt/tensorrt/test/Target/TensorRT/TRT10/unary.mlir

Current versions of TensorRT allow unary inputs to be scalar. This change restricts the 1D check to TensorRT 8 so that newer versions are able to accept scalar inputs.

Allows scalars in unary operations

---

mlir-tensorrt/tensorrt/lib/TensorRT/IR/Verification.cpp
mlir-tensorrt/tensorrt/test/Dialect/TensorRT/roundtrip.mlir

Skips checking that the number of input channels is divisible by group count if the input shape is dynamic.

Skips deconv shape validation for dynamic shapes

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td

Enables int4 inputs to `tensorrt.shape` and
int8 inputs to `tensorrt.select`.

Enables I4 in shape and I8 in where

---

tripy/nvtripy/frontend/tensor.py

tensor.eval also returns the evaluated tensor instead of "runtime.MemrefValue", making it a visible API to users.

Document tensor.eval, tolist

---

mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp

Works around an illegal memory access bug that is seen when allocating outputs larger than 32MB. See issue #590 for details.

Implements a workaround for an illegal memory access bug

---

tripy/README.md
tripy/docs/post0_developer_guides/00-architecture.md
tripy/docs/pre0_user_guides/00-introduction-to-tripy.md
tripy/docs/pre0_user_guides/02-compiler.md
tripy/examples/nanogpt/example.py
tripy/examples/segment-anything-model-v2/sam2/build_sam.py
tripy/examples/segment-anything-model-v2/sam2/modeling/memory_attention.py
tripy/examples/segment-anything-model-v2/sam2/modeling/sam2_base.py
tripy/nvtripy/backend/api/compile.py
tripy/nvtripy/backend/api/executable.py
tripy/nvtripy/backend/api/input_info.py
tripy/nvtripy/backend/api/stream.py
tripy/nvtripy/frontend/ops/unary/sigmoid.py
tripy/nvtripy/frontend/ops/unary/silu.py
tripy/nvtripy/frontend/tensor.py
tripy/tests/backend/api/test_compile.py
tripy/tests/backend/api/test_executable.py
tripy/tests/backend/api/test_stream.py
tripy/tests/integration/conftest.py
tripy/tests/integration/test_plugin.py

[Updates sigmoid/silu documentation, simplifies silu implementation](https://github.com/NVIDIA/TensorRT-Incubator/commit/337e92996c2516dc8a95498fe58abe7ed9c7b7dd)
[Updates executables to reject tensors that are not GPU constants.](https://github.com/NVIDIA/TensorRT-Incubator/commit/d735115f79461b294123e1fe444104401b38e9e4)

Simplifies silu, updates executables to reject tensors that are not GPU constants

---

.github/workflows/mlir-tensorrt-ci.yml

This PR disables TRT 8 check in MLIR-TensorRT CI. Most customers have moved to TensorRT 10 which reduces importance of keep TRT 8 in CI.

[NFC] Disable TRT 8 check in MLIR-TensorRT CI

---

mlir-tensorrt/compiler/include/mlir-tensorrt/Registration/RegisterMlirTensorRtDialects.h
mlir-tensorrt/compiler/lib/CAPI/Compiler/Registration/RegisterAllDialects.cpp

The compiler CAPI was missing the registration of
LLVM externsion interfaces.

[MLIR-TensorRT] Fix compiler CAPI missing registration

---

mlir-tensorrt/compiler/test/python/mlir_tensorrt_runtime/test_runtime_api.py
mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h
mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp
mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
mlir-tensorrt/tensorrt/test/lib/Target/TestPlugins.cpp

Adds an API to the stream wrapper to get a pointer to the underlying CUDA stream. This is useful for interoperating with other CUDA libraries.

Adds an API to get the stream pointer

---

tripy/nvtripy/backend/api/executable.py
tripy/nvtripy/frontend/tensor.py
tripy/nvtripy/trace/ops/constant.py
tripy/nvtripy/trace/tensor.py
tripy/tests/utils/wrappers/test_interface.py

Speeds up `Tensor.__init__` if the input data is a DLPack tensor and no cast/copy is needed. This usage of the constructor is often seen in runtime code that interoperates with frameworks, and so we want to minimze any overheads introduced by Tripy.
This change disables the function registry dispatch logic for `__init__` and enables a fast path that skips fetching stack information. Also drops the explicit `fast_init` constructor since we now automatically determine when the fast path can be used.
Also optimizes `Constant.__init__` with a custom implementation that avoids the overheads of the more general parent constructor.

Speeds up Tensor.__init__ in certain cases, optimizes Constant.__init__

---

tripy/CONTRIBUTING.md
tripy/examples/segment-anything-model-v2/configs/sam2_hiera_l.yaml
tripy/examples/segment-anything-model-v2/configs/sam2_hiera_s.yaml
tripy/examples/segment-anything-model-v2/configs/sam2_hiera_t.yaml
tripy/examples/segment-anything-model-v2/sam2/build_sam.py
tripy/examples/segment-anything-model-v2/sam2/modeling/backbones/image_encoder.py
tripy/examples/segment-anything-model-v2/sam2/modeling/sam2_base.py
tripy/examples/segment-anything-model-v2/video_demo.py
tripy/nvtripy/__init__.py
tripy/nvtripy/backend/api/stream.py
tripy/pyproject.toml
tripy/tests/backend/api/test_stream.py

Adds `--cap-add=SYS_PTRACE` to docker commands so that `gdb` can be used with child processes in the container.
Removes unnecessary stream synchronize in SAMv2 demo.

Various improvements to SAMv2 demo

---

.github/workflows/mlir-tensorrt-ci.yml
mlir-tensorrt/build_tools/scripts/cicd_build.sh

This PR updates mlir-tensorrt CI to save cache after each (normal and ASAN) build. Previously, cache was being saved at the end of job but this is problematic when build needs to run again (which takes long time!) just because of single test failure.
Now, `cicd_build.sh` script is separated in build and test phases. Cache is saved immediately after build. This way, even when test fails, next build is faster.

[mlir-tensorrt] Update CI to save cache after build

---

mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp
mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTDialect.td
mlir-tensorrt/tensorrt/lib/Target/TensorRTEncodingOpInterface/NetworkEncoder.cpp
mlir-tensorrt/tensorrt/lib/Target/TranslateToTensorRT.cpp

For now we query an environment variable `MTRT_TENSORRT_NVTX` to set the nvtx profiling verbosity. This is not ideal because it cannot support per-engine profiling verbosity. We will change that with a runtime option for TRT module.

[TensorRT] Sets TRT layer metadata and nvtx profiling verbosity

---

mlir-tensorrt/CONTRIBUTING.md

This PR updates `CONTRIBUTING.md` by adding information about spinning dev container inside and outside of VS Code.

[mlir-tensorrt] Update `CONTRIBUTING.md`

---

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTDialect.td
mlir-tensorrt/tensorrt/lib/Target/TensorRTEncodingOpInterface/NetworkEncoder.cpp

Extracts TRT layer metadata from FusedLocation.metadata. Also removes the "metadata" string from TRT dialect as it is no longer needed.

[TensorRT] Extract layer metadata from FusedLocation

---

.github/workflows/mlir-tensorrt-ci.yml

Previously we were using free CPU runner hosted by GitHub and to avoid OOM errors we were cleaning up the disk space. Recently, we have shifted to self-hosted runner and we don't need disk clean up stage. This PR cleans CI for it.

[mlir-tensorrt] Fix CI
