tripy/tripy/backend/mlir/executor.py, tripy/tripy/backend/mlir/utils.py, tripy/tripy/common/array.py, tripy/tripy/flat_ir/ops/constant.py
Thanks @christopherbate for finding this issue.
=> Avoid reinitializing RuntimeClient

tripy/tripy/frontend/trace/ops/gather.py
Note: https://github.com/NVIDIA/TensorRT-Incubator/issues/52 will add more integration tests for Gather operation.
Fixes two issues with Gather op:
1. `FlatIRTensor` constructor was not provided `rank`.
2. When `axis>0`, slicing second half of shape tensor was incorrect.
=> [tripy] Fix gather operation when axis > 0

tripy/tripy/backend/mlir/utils.py, tripy/tripy/flat_ir/flat_ir.py, tripy/tripy/flat_ir/ops/copy.py
Simplify code to fetch mlir tensor `type` using mlir utils.
=> Use get_op_result_or_value instead of conditional checks

tripy/docs/post0_developer_guides/how-to-add-new-ops.md
Fix test broken by https://github.com/NVIDIA/TensorRT-Incubator/pull/83
=> Remove stale import of static shape iota op

CONTRIBUTING.md
Depends on https://github.com/NVIDIA/TensorRT-Incubator/pull/48 and https://github.com/NVIDIA/TensorRT-Incubator/pull/49.
=> Add Top level contributing guideline

tripy/tripy/frontend/module/conv_transpose.py, tripy/tripy/frontend/module/convolution.py, tripy/tripy/frontend/module/groupnorm.py, tripy/tripy/frontend/module/layernorm.py
Avoids expensive shape of shape evaluation.
L0 Test: 1959 passed, 47 skipped, 1 deselected, 1 warning
=> Update Convolution & GroupNorm for dynamic shapes

.github/workflows/tripy-l1.yml
Proper fix for mounting tripy directory in the contianer.
=> Update L1 yml: Proper fix for mounting tripy directory

.github/workflows/mlir-tensorrt-ci.yml, mlir-tensorrt/executor/CMakeLists.txt, mlir-tensorrt/executor/test/IntegrationTests/lit.local.cfg, mlir-tensorrt/executor/test/IntegrationTests/stream.mlir, mlir-tensorrt/executor/test/Translation/translate-to-runtime-executable.mlir, mlir-tensorrt/executor/test/Unit/CAPI/CMakeLists.txt, mlir-tensorrt/executor/test/executor-runner/invalid.mlir, mlir-tensorrt/test/Target/Lua/IntegrationTests/ClusteringDynamicShape/lit.local.cfg, mlir-tensorrt/test/Target/Lua/IntegrationTests/buffer-ops-f8E4M3FN.mlir
This MR adds CI workflow for MLIR-TensorRT project which runs PR created against main branch (except draft PR). This workflow performs format checking and runs LIT tests.
=> Add MLIR-TensorRT CI workflow

tripy/tripy/frontend/trace/ops/reshape.py
=> Add verification to flatten op

tripy/tests/integration/test_binaryelementwise.py, tripy/tripy/frontend/trace/ops/binary_elementwise.py
Fixes https://github.com/NVIDIA/TensorRT-Incubator/issues/201
=> Add modulo operator

mlir-tensorrt/test/python/mlir_tensorrt_compiler/compiler_api/test_layer_metadata_callback.py
Corrects checks in layer metadata callback test
=> [test] Corrects checks in layer metadata callback test

.github/workflows/mlir-tensorrt-ci.yml
Reverts NVIDIA/TensorRT-Incubator#255
=> Revert "[mlir-tensorrt] Add commit message check to CI"

mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp
This commit adds the OutputAllocator and OutputAllocatorImpl classes to manage memory allocation for TensorRT outputs. It provides methods for setting and retrieving tensor data, shape, and allocation information. Implemented `OutputDescriptor` class to aid in extracting rank, result, ptr etc. from memory buffer refernced by output descriptor pointer. Also, added a lua method to ensure allocators lifetime is coupled with the session.
=> [Lua/TensorRTModule] Implement OutputAllocator for TensorRT execution

.github/CODEOWNERS, mlir-tensorrt/README.md, mlir-tensorrt/python/requirements-dev.txt
This PR makes the following changes,
- Add code owners for `mir-tensorrt` part to help review.
- Add torch as dependency in `requirements-dev.txt`. Torch based test is used in Python API.
- Fix an error in README.
=> [NFC][mlir-tensorrt] Fix minor issues

tripy/tests/frontend/test_utils.py, tripy/tripy/backend/api/compile.py, tripy/tripy/constraints.py, tripy/tripy/frontend/utils.py, tripy/tripy/utils/utils.py
=> [Tripy] Handle variadic arguments in `preprocess_args` for the `convert_to_tensors` decorator

.github/workflows/tripy-release.yml, tripy/Dockerfile, tripy/README.md, tripy/RELEASE.md, tripy/examples/nanogpt/model.py, tripy/pyproject.toml, tripy/setup.py, tripy/tests/test_packaging.py
- Updates permissions for the release pipeline so it is allowed to push new releases.
- Adds a separate wheel building flow so that we can include stub files (see RELEASE.md for details).
=> Fixes release pipeline, adds separate build flow to include stubs

tripy/tests/test_function_registry.py, tripy/tripy/function_registry.py
=> [Tripy] Check type annotations for variadic arguments in the function registry

mlir-tensorrt/tensorrt/lib/Utils/ShapeUtils.cpp, mlir-tensorrt/tensorrt/test/Dialect/TensorRT/invalid.mlir
=> Move internal changes

.github/workflows/mlir-tensorrt-ci.yml
This PR fixes CPM cache path in mlir-tensorrt CI.
=> [mlir-tensorrt][CI] Fix CPM cache path

tripy/docs/post0_developer_guides/how-to-add-new-ops.md, tripy/docs/pre0_user_guides/00-introduction-to-tripy.md, tripy/examples/nanogpt/README.md, tripy/tests/backend/api/test_compile.py, tripy/tests/backend/api/test_executable.py, tripy/tests/backend/api/test_stream.py, tripy/tests/frontend/module/test_module.py, tripy/tests/frontend/module/test_parameter.py, tripy/tests/frontend/module/test_sequential.py, tripy/tests/frontend/ops/test_equal.py, tripy/tests/helper.py, tripy/tests/integration/test_allclose.py, tripy/tests/integration/test_arange.py, tripy/tests/integration/test_equal.py, tripy/tests/integration/test_flip.py, tripy/tests/test_examples.py, tripy/tripy/backend/api/stream.py, tripy/tripy/frontend/module/module.py, tripy/tripy/frontend/ops/allclose.py, tripy/tripy/frontend/ops/equal.py
- [Adds a tp.equal API and updates tests to use it where applicable](https://github.com/NVIDIA/TensorRT-Incubator/commit/087be0d86cb2f0ece16cc92f3f66b0ac5e968fd7)
- [Cleans up printing of modules, adds automatic conversion to Parameter when setting attributes](https://github.com/NVIDIA/TensorRT-Incubator/commit/53f17ea35ba1f5266f462663bd6e04ed7b620349)
- [Updates nanoGPT test to use standard regexs](https://github.com/NVIDIA/TensorRT-Incubator/commit/e2b04cdebe6f68100ace8d81de6b0cae9f291871)
=> Adds tp.equal, improves Module prints, fixes nanoGPT

mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/CUDA/CUDAModule.cpp, mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/NCCL/NCCLModule.cpp
=> [mlir-tensorrt] NFC: [executor] update NCCL debug logging in runtime

tripy/pyproject.toml
This reverts commit 2c6cc1a8a824356af2a8ccfe218326fa8c61175a.
=> Revert "[Tripy] Add tripy for setup tools to pass L1 test (#413)"

tripy/examples/segment-anything-model-v2/sam2/build_sam.py
Use singleton class to manage sharing of models across image and video pipeline
=> Manage peak memory in SAM2

mlir-tensorrt/tensorrt/include/mlir-tensorrt-dialect/TensorRT/IR/TensorRTOps.td, mlir-tensorrt/tensorrt/lib/TensorRT/IR/TensorRTVersionCompatibility.cpp, mlir-tensorrt/tensorrt/lib/TensorRT/IR/TypeInferenceInterfaceImpls.cpp, mlir-tensorrt/tensorrt/lib/TensorRT/IR/Verification.cpp, mlir-tensorrt/tensorrt/lib/TensorRT/Transforms/BroadcastElimination.cpp, mlir-tensorrt/tensorrt/test/Dialect/TensorRT/broadcast-elimination.mlir, mlir-tensorrt/tensorrt/test/Target/TensorRT/cast.mlir
Ports some WIP MLIR-TRT changes to the trt-dialect branch so we don't have to wait for them to be merged into `main` first.
=> Ports MLIR-TRT changes to TRT dialect branch

tripy/nvtripy/frontend/ops/__init__.py, tripy/nvtripy/frontend/ops/expand.py, tripy/nvtripy/frontend/ops/reshape.py, tripy/nvtripy/frontend/ops/slice.py, tripy/nvtripy/frontend/ops/unary/__init__.py, tripy/nvtripy/frontend/ops/unary/abs.py, tripy/nvtripy/frontend/ops/utils.py, tripy/nvtripy/trace/ops/slice.py
Depends on https://github.com/NVIDIA/TensorRT-Incubator/pull/527
[Implements __abs__ for tensors](https://github.com/NVIDIA/TensorRT-Incubator/commit/58e499987e9d63df5000fb21d3169ef9253d99ae)
[Ports slice to TRT dialect](https://github.com/NVIDIA/TensorRT-Incubator/commit/aa7706611c338db37699986f0785978c882c8d06)
=> Ports `slice` to TRT dialect

tripy/nvtripy/backend/mlir/compiler.py, tripy/nvtripy/backend/mlir/utils.py, tripy/nvtripy/common/exception.py, tripy/nvtripy/frontend/ops/binary/create.py, tripy/nvtripy/frontend/ops/matmul.py, tripy/nvtripy/frontend/ops/utils.py, tripy/nvtripy/trace/ops/matmul.py, tripy/nvtripy/trace/trace.py
[Ports MatrixMultiply to TRT dialect](https://github.com/NVIDIA/TensorRT-Incubator/commit/7051e69275c3e1ea23efc787c49e8970e4db27a2)
[Updates error reporting logic to work with Trace instead of FlatIR](https://github.com/NVIDIA/TensorRT-Incubator/commit/bc77fef0eb11f94eaf5784a3ff949ef88014e6e6)
=> Ports MatrixMultiply to TRT dialect, updates error reporting logic

mlir-tensorrt/CMakeLists.txt, mlir-tensorrt/build_tools/cmake/Dependencies.cmake, mlir-tensorrt/build_tools/cmake/TensorRTDownloadURL.cmake, mlir-tensorrt/build_tools/scripts/cicd_build.sh
Updates the default version we compile against to 10.9. Also corrects the build number to match the latest release.
=> Updates default TensorRT version to 10.9

mlir-tensorrt/tensorrt/lib/TensorRT/Transforms/BroadcastElimination.cpp, mlir-tensorrt/tensorrt/test/Dialect/TensorRT/broadcast-elimination.mlir
When multiple input operands of an operation (e.g. elementwise, select) are being broadcasted along the same dimension to a larger one, we cannot eliminate the broadcast. The logic to do this was already in place, but did not account for dynamic dimensions.
=> Avoids broadcast elimination for dynamic shapes

mlir-tensorrt/executor/include/mlir-executor-c/Runtime/Runtime.h, mlir-tensorrt/executor/lib/CAPI/Runtime/Runtime.cpp, mlir-tensorrt/executor/lib/Runtime/API/API.cpp, mlir-tensorrt/executor/lib/Runtime/Backend/Lua/Modules/TensorRT/TensorRTModule.cpp, mlir-tensorrt/python/bindings/Runtime/RuntimePyBind.cpp
Adds some extra information to debug prints. Also adds a __str__ method to `PyStream` so we can see the underlying stream pointer easily.
=> Adds extra debugging information

mlir-tensorrt/CMakePresets.json, mlir-tensorrt/build_tools/scripts/build_wheels.sh
This PR fixes an issue in wheel release bash script.
=> [mlir-tensorrt] Wheel release script fix

.github/workflows/mlir-tensorrt-ci.yml
This PR changes CI runner for MLIR-TEnsorRT project from CPU only to GPU.
=> [CI] Start using GPU runner for MLIR-TensorRT CI

tripy/examples/segment-anything-model-v2/sam2/modeling/sam2_utils.py
Naive performance test results indicate the new implementation is about 50% faster
```
LayerNorm2d_TP1 (Direct Implementation) took 0.0059s for 100 iterations
LayerNorm2d_TP2 (LayerNorm-based) took 0.0038s for 100 iterations
```
=> Update LayerNorm2D to use TRT normalization API

tripy/nvtripy/common/exception.py, tripy/nvtripy/trace/trace.py
Updates our Trace->MLIR translation to include metadata for each layer that includes stack information and details about the Trace operation.
=> Updates MLIR to include layer metadata
